name: motion_tab_bar_v2
description: An animated Bottom Navigation Bar for Flutter apps, icon animates into place, colors are customizable.
version: 0.5.0
repository: https://github.com/kimmanwky/Motion-Tab-Bar
homepage: https://github.com/kimmanwky/Motion-Tab-Bar

environment:
  sdk: '>=2.12.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
